name: CI

on: [push] #This pipleline will get triggered on push (or) whenever there is a push in the repository, no matter which branch 
           # that is we always want to run this pipeline.
jobs:
 sast_scan: #sast scan or sast security job.
  name: Run Bandit scan   # we are running bandit scan.
  runs-on: ubuntu-latest  # Run bandit on ubuntu machine.

  steps:
  - name: Checkout code        # will start by checking the code.
    uses: actions/checkout@v2  # Checks out our repository code.

  - name: Set up python # As no tools are pre-installed, we need to install python.We need python because bandit is a python package.
    uses: actions/setup-python@v2 #
    with: 
      python-version: 3.8 #sets up the python version 3.8.

  - name: Install bandit   # Installing bandit tool.
    run: pip install bandit

  - name: Run Bandit scan   # execute scan using bandit tool.
    run: bandit -ll -ii -r . -f json --output bandit-report.json  # scans everything in current folder.

  - name: Upload Artifact
    uses: actions/upload-artifact@v4
    if: always()     # this step will always execute even if any one of the precious step fails.
    with:
     name: bandit-findings
     path: bandit-report.json
   
 image_scan:
   name: Build Image and Run Image Scan
   runs-on: ubuntu-latest

   steps:
   - name: Set up Docker
     uses: docker-practice/actions-setup-docker@v1
     with:
      docker_version: '20.10.7'

   - name: Build Docker image
     uses: docker build -f Dockerfile -t myapp:latest .

   - name: Docker Scout scan
     run: |
       curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
       echo ${{ secrets.REPO_PWD }} | docker login -u ${{ secrets.REPO_USER }} --password-stdin
       
       docker scout quickview
       docker scout cves
       


   
  
